### PR TITLE
Feat/inct 181

### PR DESCRIPTION
**Pull request by elem15**
- [x] - responsible layout to profile on desktop 
- [x] - protect pofile and home route from unauthorized user

### CODE REVIEW

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Review by grippiby — APPROVED** [review]

**Comment by grippiby** [comment]
все логично. Можно мерджить!

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Comment by elem15** [comment]
run build production

**Pull request merged**
